#!/usr/bin/ruby
# encoding: utf-8

# Our dir of media to be tagged
class MusicCollection
  def initialize
    files = Dir.glob('**/*').reject { |f| File.directory? f }
    # Filter out ones that don't match the filetypes
    filetypes = ['.flac', '.ogg', '.mp3']
    files.select! do |f|
      filetypes.any? { |ft| /#{ Regexp.escape ft }$/i =~ f }
    end
    # Filter out files that already have a BPM tag name
    # FIXME
  end
end

MusicCollection.new.cp
