#!/usr/bin/env ruby

#
# bpm_tagdir
#
# Run's Mark Hill's bpm-tag script on all mp3, flac, and ogg media files in
# the CWD (and sub directories).
#
# Skips files with the BPM in the file name, like this:
#   Remarc - Suicidal (165 BPM).flac
#

def calculate_bpm(file, bot_bpm = 135, top_bpm = 250, force = false)
  `bpm-tag -m #{bot_bpm} -x #{top_bpm} #{'-f' if force} #{file.shellescape}`
end

require 'shellwords'

Thread.abort_on_exception = true

filetypes = ['.flac', '.ogg', '.mp3']

files = Dir.glob('**/*').reject { |f| File.directory? f }

# Filter out ones that don't match the filetypes
files.select! do |f|
  filetypes.any? { |ft| /#{ Regexp.escape ft }$/i =~ f }
end

# Filter out ones that already have bpms in the names
files.reject! do |f|
  f.match(/.+\(\d{2,4}.?\d{0,4} BPM\).\w+\z/)
end

puts "#{files.size} tracks to process"

# Process files in parallel
files.each.with_index do |file|
  sleep 1 until Thread.list.size < 5
  Thread.new do
    calculate_bpm file
  end
end

# Wait until we're done
sleep 1 until Thread.list.size == 1

puts '...done!'
